# Generated by Django 4.2.14 on 2024-07-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categories', models.CharField(choices=[('starters', 'Starters'), ('maindishes', 'Main dishes'), ('deserts', 'Deserts')], max_length=50)),
            ],
        ),
    ]
