# Generated by Django 4.2.14 on 2024-08-21 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello_alps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField()),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('opening_hour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello_alps.openinghour')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello_alps.table')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Reservation',
                'verbose_name_plural': 'User Reservations',
                'ordering': ['date', 'time'],
            },
        ),
    ]
