# Generated by Django 4.2.14 on 2024-08-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_alps', '0002_openinghour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
