# Generated by Django 4.2.14 on 2024-08-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_alps', '0003_alter_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='categories',
            field=models.CharField(choices=[('starters', 'Starters'), ('maindishes', 'Main dishes'), ('pizza', 'Pizza'), ('desserts', 'Desserts')], max_length=50),
        ),
    ]
