# Generated by Django 4.2.14 on 2024-08-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_alps', '0004_alter_menu_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved')], default='available')),
            ],
        ),
    ]
